# Postgres database connection details
spring:
  datasource:
    url: "jdbc:postgresql://smartaviator_db:5432/smartaviator_db"
    username: "postgres"
    password: "mypass"
  # Creation of database
  jpa:
    hibernate:
      ddl-auto: "create-drop"