version: '3.5'

services:
  postgres:
    container_name: aviation_postgres_container
    image: postgres
    environment:
      PGTZ: 'UTC'
      TZ: 'UTC'
      POSTGRES_DB: aviation_postgres_container
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypass}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: