global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'smartaviator-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['smartaviator-app:9000']
        labels:
          application: 'smartaviator'